#!/bin/bash

# Easy connect to mysql

group="trunk"
user=`whoami`
u="${user:0:1}"

HL='\033[1;33m'  # yellow
ERR='\033[0;31m' # red
HOK='\033[1;32m' # green
NC='\033[0m'     # No Color
BOLD=$(tput bold)
NORMAL=$(tput sgr0)

function usage {
    echo -e "Usage: ${HL}$0 <service> [<group>]${NC}
    <service> is core, mms, stats etc
    <group>   is ${HL}${u}${NC} for $user, ${HL}t${NC} for trunk (defaults to trunk)"
}

if [ $# -eq 0 ] ; then
    usage;
    exit 0
fi

if [ "$2" == "$u" ] ; then
    group="$user"
else
    echo
    echo -e ">>> ${ERR}${BOLD}ACHTUNG!!! USING TRUNK DATABASES${NORMAL}${NC} <<<"
    echo
fi

conf=~/db/$group/$1.cnf

if [ ! -r "$conf" ] ; then
    echo -e "${ERR}Config file $conf not found or is not readable${NC}"
    exit 1
fi

mysql --defaults-file=$conf
